### ISSUE TITLE
GamestreamLauncher.exe missing from commit

### ISSUE THREAD

**Issue by malarivi** [loueradun/GamestreamLauncher#2]
Do I need to compile? I don't see a GamestreamLauncher.exe in ./bin?

**Comment by malarivi** [comment]
I'm using this with a vmrun wrapper to suspend all VMWare Workstation VM's that are running at game launch.

**Comment by loueradun** [comment]
No, the compiled releases are found here:
https://github.com/loueradun/GamestreamLauncher/releases

Please note that I should be publishing a new build shortly.
