### ISSUE TITLE
Final scripts not run when exiting session using Gamestream Stop button

### ISSUE THREAD

**Issue by nonamer66** [loueradun/GamestreamLauncher#3]
Thank you for this app, but I have an issue with the stop script... I have an ultrawide monitor and so I have to lower my screen resolution for gamestream to 1920x1080. Here is the current config I have and it will not switch back to my default of 2560x1080 res. after closing.

`<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <configSections>
        <sectionGroup name="userSettings" type="System.Configuration.UserSettingsGroup, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" >
            <section name="GamestreamLauncher.Properties.Settings" type="System.Configuration.ClientSettingsSection, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" allowExeDefinition="MachineToLocalUser" requirePermission="false" />
        </sectionGroup>
    </configSections>
    <userSettings>
        <GamestreamLauncher.Properties.Settings>
            <setting name="AppName" serializeAs="String">
                <value>BigBox 2.0</value>
            </setting>
            <setting name="ScriptsEnabled" serializeAs="String">
                <value>True</value>
            </setting>
            <setting name="StartupScriptPath" serializeAs="String">
                <value>C:\Program Files (x86)\12noon Display Changer\dc64.exe</value>
            </setting>
            <setting name="AwesomeMinerIP" serializeAs="String">
                <value>127.0.0.1</value>
            </setting>
            <setting name="StartupScriptParameters" serializeAs="String">
                <value>-width=1920 -height=1080</value>
            </setting>
            <setting name="MultiMonSwitchEnabled" serializeAs="String">
                <value>False</value>
            </setting>
            <setting name="AwesomeMinerSwitchEnabled" serializeAs="String">
                <value>False</value>
            </setting>
            <setting name="ShutdownScriptParameters" serializeAs="String">
                <value>-width=2560 -height=1080</value>
            </setting>
            <setting name="AwesomeMinerPort" serializeAs="String">
                <value />
            </setting>
            <setting name="ShutdownScriptPath" serializeAs="String">
                <value>C:\Program Files (x86)\12noon Display Changer\dc64.exe</value>
            </setting>
            <setting name="AppPath" serializeAs="String">
                <value>Z:\Launchbox\LaunchBox\BigBox.exe</value>
            </setting>
            <setting name="AwesomeMinerKey" serializeAs="String">
                <value />
            </setting>
        </GamestreamLauncher.Properties.Settings>
    </userSettings>
</configuration>`

**Comment by loueradun** [comment]
I have a new version I should be publishing soon that will allow you to just set the Gamestream resolution without dealing with any custom scripts.

How do you generally close the gamestream session (using the quit button from the Gamestream menu, or are you quiting Bigbox directly)?

**Comment by nonamer66** [comment]
> I have a new version I should be publishing soon that will allow you to just set the Gamestream resolution without dealing with any custom scripts.
> 
> How do you generally close the gamestream session (using the quit button from the Gamestream menu, or are you quiting Bigbox directly)?

Thank you. I use the quit button from the gamestream.

**Comment by loueradun** [comment]
I have been able to confirm that all the final launcher scripts, including the Custom Stop Script are not being run when the service is closed through the Gamestream quit button.  This was previously working, so I would guess that NVidia must have changed something in some recent updates.  I'll need to get this sorted before releasing the next build.

I appreciate the feedback as I hadn't noticed this issue since I always quit the application launched through the launcher directly, as the Gamestream quit button is effectively the same as hard closing all applications opened through the session.

**Comment by loueradun** [comment]
Closing as fixed in v1.3.0.  if you are still experiencing issues please let me know.
