### ISSUE TITLE
Monitor Toggle Addition

### ISSUE THREAD

**Issue by Tierney11290** [loueradun/GamestreamLauncher#6]
This is less of an issue and more of request if anything as GamestreamLauncher is technically working correctly already. This tool is exactly what I need but was wondering if it were possible to add onto the Monitor Toggle feature? Instead of just disabling the secondary monitor by using the Monitor Toggle checkbox, an option to disable the primary monitor and used the secondary instead would be great. The reason for this is that I have a 32:9 (5120x1440) monitor as my main, but it has issues when it comes to Gamestream and it will not stream in 4k HDR (only 1080p HDR, even when using Nvidia Control Panel). My secondary monitor is 16:9 (3840x2160) w/ HDR though. To make it work on Gamestream, one could either make the 16:9 monitor the primary or unplug the 32:9 monitor. The problem with the former is that when played at the PC, all games will show up on that monitor rather than the 32:9 monitor. The problem with the latter is that you have to plug it back in everytime. Both I am trying to avoid for the sake of automation and ease of use (ironically I find myself here!). In theory, the best workaround would be to disable my primary 32:9 monitor when Gamestream is launched, therefore making the 16:9 monitor the primary and allowing for GameStream to work correctly in 4k HDR.

For what it's worth, I created a batch file that will utilize the built-in Windows program Displayswitch.exe with a parameter of "/external" (turn primary off, keep secondary on) then start Playnite, wait for Playnite to close, then continue the script with Displayswitch.exe with a parameter of "/internal" (turn off secondary, reactivate primary), wait a few seconds then run Displayswitch.exe again but with the "/extend" parameter (extend desktop to secondary monitor). The latter part is a bit odd, but it's required because that's how Displayswitch.exe activates monitors unfortunately. Regardless, this all works exactly the way I want it to but it seems when Gamestream is launched from the Nvidia Shield, it captures the primary monitor desktop too quickly and therefore shows a blank screen on the Nvidia Shield rather than the image of the second monitor.

I am not sure how exactly how MultiMonitorTool.exe integrates with GamestreamLauncher to be honest as there is no instruction on how to do so. I assumed it's supposed to be seamless but not sure.

**Comment by loueradun** [comment]
I'm not sure if any changes to the launcher would accomplish what you want it to do.  By the time the launcher runs, the stream has already been initiated.  I'm not sure that I can disable/change the main monitor at that point, and it likely streams whatever screen was the primary when the stream was initiated.  It sounds like you may be better off using the script that you have now to change the monitor config before/after the stream.  Somehow you need to execute your script before actually starting the stream, but I am not sure how that would be done at this time (short of creating a "custom game" that ran said script).

The code for interacting with MultiMonitorTool is pretty simple.  It is saving the current monitor config to an xml file, disabling everything except the main display, then reloading the saved config after the stream ends.

My current monitor does not support HDR, but my TV does.  It may be possible to get HDR to work by using a modified monitor EDID to trick Windows into thinking it supports HDR.  I may have to investigate this some more.

**Comment by Tierney11290** [comment]
> I'm not sure if any changes to the launcher would accomplish what you want it to do. By the time the launcher runs, the stream has already been initiated. I'm not sure that I can disable/change the main monitor at that point, and it likely streams whatever screen was the primary when the stream was initiated. It sounds like you may be better off using the script that you have now to change the monitor config before/after the stream. Somehow you need to execute your script before actually starting the stream, but I am not sure how that would be done at this time (short of creating a "custom game" that ran said script).
> 
> The code for interacting with MultiMonitorTool is pretty simple. It is saving the current monitor config to an xml file, disabling everything except the main display, then reloading the saved config after the stream ends.
> 
> My current monitor does not support HDR, but my TV does. It may be possible to get HDR to work by using a modified monitor EDID to trick Windows into thinking it supports HDR. I may have to investigate this some more.

I had a feeling that might be the case! Unfortunate but no worries. Maybe Nvidia will implement the change some day, though not counting on it since they seem to have all but abandoned Gamestream for GeForce Now. I did end up figuring out MultiMonitorTool. It's super easy as you said and works great in conjunction with Command Prompt. I did consider the EDID trick for HDR but needed a new second monitor anyhow so I decided to go with a cheaper 4k HDR monitor.

Thanks for the reply. I'll go ahead and close this for now.

**Comment by Tierney11290** [comment]
For anyone looking for a solution, some genius created this official extension for Playnite and it works great for Gamestream!

https://playnite.link/forum/thread-265.html
